# Generated by Django 3.1.5 on 2021-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseDate', models.DateField()),
                ('movieName', models.CharField(max_length=30)),
                ('starMale', models.CharField(max_length=30)),
                ('starFemale', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
